// packages/ui/src/snippet.tsx
import { FC, HTMLAttributes, useMemo } from 'react'
import cn from 'clsx'
import { highlight } from 'sugar-high'

const Snippet: FC<HTMLAttributes<HTMLPreElement>> = ({
  children,
  className,
  ...props
}) => {
  const __html = useMemo(
    () => (children ? highlight(children.toString()!) : ''),
    [children]
  )
  return (
    <pre
      className={cn(
        'border border-accents-2 rounded-md bg-accents-1 overflow-x-auto p-6',
        className
      )}
      {...props}
    >
      <code dangerouslySetInnerHTML={{ __html }} />
    </pre>
  )
}

export default Snippet

// packages/ui-svelte/src/Snippet.svelte
<script>
  import clsx from 'clsx'
  export let className = ''
</script>

<pre>
    <code class={clsx('root', className)}>
        <slot />
    </code>
</pre>

<style>
  .root {
    border-color: var(--accents-2);
    border-width: 1px;
    border-radius: 0.375rem;
    background-color: var(--accents-1);
    overflow-x: auto;
    padding: 1.5rem;
  }
</style>
