// internal/packages/ui/src/snippet.tsx
import { type HTMLAttributes } from 'react'
import clsx from 'clsx'

export const Snippet = ({
  children,
  className,
  ...props
}: HTMLAttributes<HTMLPreElement>) => (
  <pre
    className={clsx(
      'border border-accents-2 rounded-md bg-accents-1 overflow-x-auto p-6',
      className
    )}
    {...props}
  >
    {children}
  </pre>
)

// packages/ui-svelte/src/Snippet.svelte
<script>
  import clsx from 'clsx'
  export let className = ''
</script>

<pre>
    <code class={clsx('root', className)}>
        <slot />
    </code>
</pre>

<style>
  .root {
    border-color: var(--accents-2);
    border-width: 1px;
    border-radius: 0.375rem;
    background-color: var(--accents-1);
    overflow-x: auto;
    padding: 1.5rem;
  }
</style>
