// storage/postgres-sveltekit/src/lib/Table.svelte
<script>
	import ms from 'ms';
	/**
	 * @type {{id: string, name: string, email: string, image: string, createdAt: string}[]}
	 */
	export let users;
	/**
	 * @type {number}
	 */
	export let duration;

	/**
	 * @param {string | number | Date} timestamp
	 * @param {undefined} [timeOnly]
	 */
	function timeAgo(timestamp, timeOnly) {
		if (!timestamp) return 'never';
		return `${ms(Date.now() - new Date(timestamp).getTime())}${timeOnly ? '' : ' ago'}`;
	}
	function refreshPage() {
		location.reload();
	}
</script>

<div
	class="w-full max-w-xl p-12 mx-auto rounded-lg shadow-xl dark:bg-white/10 bg-white/30 ring-1 ring-gray-900/5 backdrop-blur-lg"
>
	<div class="flex items-center justify-between mb-4">
		<div class="space-y-1">
			<h2 class="text-xl font-semibold">Recent Users</h2>
			<p class="text-sm text-gray-500">
				Fetched {users.length} users in {duration ? duration : 'unknown'} ms
			</p>
		</div>
		<button on:click={refreshPage}>Refresh Page</button>
	</div>
	<div class="divide-y divide-gray-900/5">
		{#each users as user (user.id)}
			<div class="flex items-center justify-between py-3">
				<div class="flex items-center space-x-4">
					<img
						src={user.image}
						alt={user.name}
						width={48}
						height={48}
						class="rounded-full ring-1 ring-gray-900/5"
					/>
					<div class="space-y-1">
						<p class="font-medium leading-none">{user.name}</p>
						<p class="text-sm text-gray-500">{user.email}</p>
					</div>
				</div>
				<p class="text-sm text-gray-500">{timeAgo(user.createdAt)}</p>
			</div>
		{/each}
	</div>
</div>

// storage/postgres-drizzle/components/table.tsx
import { db, UsersTable } from '@/lib/drizzle';
import { timeAgo } from '@/lib/utils';
import Image from 'next/image';
import RefreshButton from './refresh-button';
import { seed } from '@/lib/seed';

export default async function Table() {
  let users;
  let startTime = Date.now();
  try {
    users = await db.select().from(UsersTable);
  } catch (e: any) {
    if (e.message === `relation "users" does not exist`) {
      console.log(
        'Table does not exist, creating and seeding it with dummy data now...'
      );
      // Table is not created yet
      await seed();
      startTime = Date.now();
      users = await db.select().from(UsersTable);
    } else {
      throw e;
    }
  }

  const duration = Date.now() - startTime;

  return (
    <div className="bg-white/30 p-12 shadow-xl ring-1 ring-gray-900/5 rounded-lg backdrop-blur-lg max-w-xl mx-auto w-full">
      <div className="flex justify-between items-center mb-4">
        <div className="space-y-1">
          <h2 className="text-xl font-semibold">Recent Users</h2>
          <p className="text-sm text-gray-500">
            Fetched {users.length} users in {duration}ms
          </p>
        </div>
        <RefreshButton />
      </div>
      <div className="divide-y divide-gray-900/5">
        {users.map((user) => (
          <div
            key={user.name}
            className="flex items-center justify-between py-3"
          >
            <div className="flex items-center space-x-4">
              <Image
                src={user.image}
                alt={user.name}
                width={48}
                height={48}
                className="rounded-full ring-1 ring-gray-900/5"
              />
              <div className="space-y-1">
                <p className="font-medium leading-none">{user.name}</p>
                <p className="text-sm text-gray-500">{user.email}</p>
              </div>
            </div>
            <p className="text-sm text-gray-500">{timeAgo(user.createdAt)}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
