// packages/ui-svelte/src/Link.svelte
<script>
  import clsx from 'clsx'
  export let href
  export let className = ''
</script>

<a class={clsx(className, 'root')} {href}>
  <slot />
</a>

<style>
  .root {
    color: var(--geist-link-color);
    text-decoration: none;
    transition: color 0.2s ease 0s;
  }

  .root:hover {
    color: var(--geist-link-color-light);
  }
</style>

// packages/ui/src/link.tsx
import type { AnchorHTMLAttributes, FC } from 'react'
import NextLink, { LinkProps } from 'next/link.js'
import cn from 'clsx'

const Link: FC<
  Exclude<LinkProps, 'passHref'> & AnchorHTMLAttributes<HTMLAnchorElement>
> = ({ href, prefetch, children, className, ...props }) => (
  <NextLink href={href} prefetch={prefetch}>
    <a
      className={cn(
        'text-link hover:text-link-light transition-colors no-underline',
        // CSS for <code/>
        '[&_code]:text-link [&_code]:hover:text-link-light [&_code]:transition-colors',
        className
      )}
      {...props}
    >
      {children}
    </a>
  </NextLink>
)

export default Link
