// starter/next-news/components/header.tsx
import Nav from './nav'
import Logo from './logo'
import Link from 'next/link'

export default function Header() {
  return (
    <header>
      <div className="left">
        <Link href="/" legacyBehavior>
          <a>
            <span className="logo">
              <Logo />
            </span>
            <span className="title">Hacker Next</span>
          </a>
        </Link>
        <div className="nav">
          <Nav />
        </div>
      </div>
      <div className="right">
        <Link href="/login" legacyBehavior>
          <a className="login">login</a>
        </Link>
      </div>

      <style jsx>{`
        header {
          background: #ffa52a;
          display: flex;
          font-size: 14px;
        }

        .logo {
          margin: 4px 5px 2px 4px;
          display: inline-block;
        }

        .left {
          flex: 9;
        }

        .right {
          flex: 1;
          text-align: right;
        }

        .title {
          font-weight: bold;
          display: inline-block;
          font-size: 14px;
          text-decoration: none;
          padding: 8px 10px 8px 4px;
          color: #000;
          vertical-align: top;
        }

        a.login {
          padding: 10px;
          display: inline-block;
          font-size: 11px;
          text-transform: uppercase;
          text-decoration: none;
          color: #000;
        }

        .login:hover {
          color: #fff;
        }

        .nav {
          display: inline-block;
          vertical-align: top;
        }

        @media (max-width: 750px) {
          .title {
            font-size: 16px;
            padding-bottom: 0;
          }

          a.login {
            padding: 24px 10px 23px;
          }

          .nav {
            display: block;
          }
        }
      `}</style>
    </header>
  )
}

// framework-boilerplates/sveltekit/src/routes/Header.svelte
<script lang="ts">
	import { page } from '$app/state';
	import logo from '$lib/images/svelte-logo.svg';
	import github from '$lib/images/github.svg';
</script>

<header>
	<div class="corner">
		<a href="https://svelte.dev/docs/kit">
			<img src={logo} alt="SvelteKit" />
		</a>
	</div>

	<nav>
		<svg viewBox="0 0 2 3" aria-hidden="true">
			<path d="M0,0 L1,2 C1.5,3 1.5,3 2,3 L2,0 Z" />
		</svg>
		<ul>
			<li aria-current={page.url.pathname === '/' ? 'page' : undefined}>
				<a href="/">Home</a>
			</li>
			<li aria-current={page.url.pathname === '/about' ? 'page' : undefined}>
				<a href="/about">About</a>
			</li>
			<li aria-current={page.url.pathname.startsWith('/sverdle') ? 'page' : undefined}>
				<a href="/sverdle">Sverdle</a>
			</li>
		</ul>
		<svg viewBox="0 0 2 3" aria-hidden="true">
			<path d="M0,0 L0,3 C0.5,3 0.5,3 1,2 L2,0 Z" />
		</svg>
	</nav>

	<div class="corner">
		<a href="https://github.com/sveltejs/kit">
			<img src={github} alt="GitHub" />
		</a>
	</div>
</header>

<style>
	header {
		display: flex;
		justify-content: space-between;
	}

	.corner {
		width: 3em;
		height: 3em;
	}

	.corner a {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 100%;
		height: 100%;
	}

	.corner img {
		width: 2em;
		height: 2em;
		object-fit: contain;
	}

	nav {
		display: flex;
		justify-content: center;
		--background: rgba(255, 255, 255, 0.7);
	}

	svg {
		width: 2em;
		height: 3em;
		display: block;
	}

	path {
		fill: var(--background);
	}

	ul {
		position: relative;
		padding: 0;
		margin: 0;
		height: 3em;
		display: flex;
		justify-content: center;
		align-items: center;
		list-style: none;
		background: var(--background);
		background-size: contain;
	}

	li {
		position: relative;
		height: 100%;
	}

	li[aria-current='page']::before {
		--size: 6px;
		content: '';
		width: 0;
		height: 0;
		position: absolute;
		top: 0;
		left: calc(50% - var(--size));
		border: var(--size) solid transparent;
		border-top: var(--size) solid var(--color-theme-1);
	}

	nav a {
		display: flex;
		height: 100%;
		align-items: center;
		padding: 0 0.5rem;
		color: var(--color-text);
		font-weight: 700;
		font-size: 0.8rem;
		text-transform: uppercase;
		letter-spacing: 0.1em;
		text-decoration: none;
		transition: color 0.2s linear;
	}

	a:hover {
		color: var(--color-theme-1);
	}
</style>
